### ISSUE TITLE
Display of items that were broken at the time of modification

### ISSUE THREAD

**Issue by MaJr-Dp** [JoeAlisson/L2jOrg#410]
Modified the Bow - broke it, the animation "blue" remained near the hand
![image](https://user-images.githubusercontent.com/13205658/92305126-e6829980-ef8c-11ea-90ba-a0544bd79062.png)

View from another character - displays broken item and modification animation
![image](https://user-images.githubusercontent.com/13205658/92305141-f8643c80-ef8c-11ea-910f-6756614f65ce.png)

**Comment by Psixxo** [comment]
and so on all weapons

**Comment by Forcecat01** [comment]
With a weapon that takes up 2 cells, that is, a two-handed weapon. the one-handed one is fine.

**Comment by vicochips** [comment]
hmm I have test with a bow and I dont have this bug, what did u do specificly ?

**Comment by Forcecat01** [comment]
Sharpening a weapon is permissible from the moment when it has an effect (blue) and when the object breaks, visually sharpening remains 

Perhaps this is due to the fact that the object was sharpened first through the admin to +10 and then broke with ordinary points. you need to test with weapons from +0 normal scrolls

**Comment by vicochips** [comment]
Well I tried with normal scrolls up to +8, it brokes after and no problem.

**Comment by JoeAlisson** [comment]
I couldn't reproduce this either

**Comment by MaJr-Dp** [comment]
Fixed long ago
