### ISSUE TITLE
Time modifier for SchemeBuffer

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#415]
Hi, you need a time modifier for **SchemeBuffer**, a config or an option so that you can specify 2-3 hours of a buff and not run every 5 minutes for a buff to the city. thank

**Comment by vicochips** [comment]
Hello !

Already exist : 

# When this is enabled it will read the "SkillDurationList" option.
# This will basically overlook the "time = x" in the skill XMLs so that you do not need to modify the L2J Datapack XMLs to increase skill duration.
# Default: False
EnableModifySkillDuration = True
# Skill duration list
# Format: skillid,newtime;skillid2,newtime2...
# Example: 
#	This enable 1h(3600) duration for songs, the "\"indicates new line,
#	and is only set for formating purposes.
#	SkillDurationList = 264,3600;265,3600;266,3600;267,3600;268,3600;\
#	269,3600;270,3600;304,3600;305,1200;306,3600;308,3600;349,3600;\
#	363,3600;364,3600
SkillDurationList = 264,3600;265,3600;266,3600;267,3600;4350,3600;269,3600;270,3600;304,3600;305,3600;1200,3600;306,3600;308,3600;349,3600;363,3600;364,3600;307,3600;276,3600;309,3600;274,3600;275,3600;272,3600;277,3600;279,3600;311,3600;365,3600;310,3600;271,3600;1204,3600;1087,3600;1085,3600;1062,3600;1243,3600;1045,3600;1048,3600;268,3600;1078,3600;1242,3600;1059,3600;1077,3600;1240,3600;1086,3600;1036,3600;1035,3600;1068,3600;1388,3600;1040,3600;1268,3600;1303,3600;1311,3600;1389,3600;366,3600;1363,3600;1356,3600;1355,3600;1357,3600;1413,3600;4702,3600;4703,3600;4700,3600;4699,3600;1323,3600;1393,3600;1392,3600;1182,3600;1189,3600;1191,3600;1352,3600;1353,3600;1032,3600;1250,3600;1256,3600;1261,3600;1249,3600;1260,3600;1005,3600;1044,3600;1047,3600;1073,3600;1257,3600;1229,3600;1251,3600;1252,3600;1005,3600;1282,3600;1043,3600;1004,3600;1362,3600;1253,3600;1284,3600;1006,3600;1007,3600;1009,3600;1310,3600;1002,3600;1309,3600;1308,3600;1391,3600;1390,3600;1364,3600;1354,3600;1415,3600;1416,3600;1414,3600;273,3600;915,3600;1003,3600;1008,3600;1260,3600;1033,3600;1542,3600;305,3600;914,3600;1548,3600;1259,3600;1268,3600;1304,3600;1397,3600

Add this :)

**Comment by Forcecat01** [comment]
thanks
