### ISSUE TITLE
Implement Auto Play

### ISSUE THREAD

**Issue by JoeAlisson** [JoeAlisson/L2jOrg#77]

**Comment by MaJr-Dp** [comment]
Automatic hunting
For convenience some gaming possibilities have been automated.

Auto-use skills
For all classes a possibility to use reinforcement skills automatically has been added:

— A skill that can be auto-used is marked with a special icon in the form of two green arrows in the upper left corner of the skill, also in the skill description is written “Auto-use”;

— In order to activate an auto-use of the skill, move the skill icon to the shortcut and right click on it;

— After the activation the skill will be auto-used in non-peace zone regions when a character has no relevant effect at the moment or the duration of the effect is less than 3 sec. 

 

Auto-use next target/macro
— Macro can again be cycled by moving it to the shortcut and right clicking on the macro icon;

— In the automation window there is a possibility to set an auto-use next target with either attack on it (if no special macro is being set) or the usage of macro on it;

— For the attack can be chosen melee or ranged next target;

— Auto-loot can be activated. Items will not immediately be put into the inventory, only after the character reach drop place close enough;
— In order to activate macro, choose all necessary actions and press the auto-use activation button;

— When teleported, auto-choice of next target function is disabled;

— In the auto-hunt interface the mode “Respectful Hunting” can be on;

— In the “Respectful Hunting” mode monsters to hunt can not be chosen as a target if they are fighting with another characters;

— If several characters attack one target, than the chosen target of the first attacker will remain, and the chosen target of the subsequent attackers will be reset and their attack actions will be stopped;

— If during the auto-hunt target does not receive any damage for some time, attack priority passes to another character;

— “Respectful Hunting” mode stores information about settings and activates settings, that have been set before the game exit, while re-enter. 
https://eu.4game.com/patchnotes/lineage2classic/154/

**Comment by vicochips** [comment]
Hello ! 

I'm back here :) I just tested new protocol version (245) with new UI. And I see that auto hunting is not working, is it normal ?

**Comment by JoeAlisson** [comment]
Hi @vicochips welcome back :)
I've Just test. it's working fine. Maybe you were on a peace zone.

**Comment by vicochips** [comment]
Well I was in catacombs, I have tested again but nothing happens. The monster is selected but nothing more :

```
: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010000                       ._...
[WARN ][2020-03-19 09:25:20][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010100                       ._...
[WARN ][2020-03-19 09:25:20][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1250/0x000000080123c040@5a906755) : d0 - 00000000 D09D0100                         ....
[WARN ][2020-03-19 09:25:36][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010000                       ._...
[WARN ][2020-03-19 09:25:36][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010100                       ._...
[WARN ][2020-03-19 09:25:36][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1250/0x000000080123c040@5a906755) : d0 - 00000000 D09D0100                         ....
[WARN ][2020-03-19 09:25:46][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010000                       ._...
[WARN ][2020-03-19 09:25:46][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010100                       ._...
[WARN ][2020-03-19 09:25:46][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1250/0x000000080123c040@5a906755) : d0 - 00000000 D09D0100                         ....
[WARN ][2020-03-19 09:26:41][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010000                       ._...
[WARN ][2020-03-19 09:26:41][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010100                       ._...
[WARN ][2020-03-19 09:26:41][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1250/0x000000080123c040@5a906755) : d0 - 00000000 D09D0100                         ....
[WARN ][2020-03-19 09:27:07][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010000                       ._...
[WARN ][2020-03-19 09:27:07][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_INTERACT_MODIFY) : d0 - 00000000 D05F010100                       ._...
[WARN ][2020-03-19 09:27:07][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1250/0x000000080123c040@5a906755) : d0 - 00000000 D09D010
```

**Comment by JoeAlisson** [comment]
I'll check as soon I get home. Can you tell me the exact location on catacombs ?

These are just warnings to non implemented packets sended by client. These specifically is a packet sended when something is changed on options. Is not important at moment :)

**Comment by vicochips** [comment]
Hey :), here is a link of the img https://i.imgur.com/Gdx1H5Z.jpg

**Comment by AlegriaFerrato** [comment]
> Hey :), here is a link of the img https://i.imgur.com/Gdx1H5Z.jpg

Put the attack on the panel and right-click on it, everything works for me.

**Comment by AlegriaFerrato** [comment]
> I'll check as soon I get home. Can you tell me the exact location on catacombs ?
> 
> These are just warnings to non implemented packets sended by client. These specifically is a packet sended when something is changed on options. Is not important at moment :)

Joe, I know that this is not so important now, but I am interested in the question, is there any plans to implement L-Shop?
Shop for L coins.
thx

**Comment by vicochips** [comment]
HAHA i'm so noob bro!

**Comment by AlegriaFerrato** [comment]
> HAHA i'm so noob bro!

Oh, I tests, ocean bugs skills :(
Joe, ready :D I posts evening bug report and error packets))

**Comment by JoeAlisson** [comment]
> Joe, I know that this is not so important now, but I am interested in the question, is there any plans to implement L-Shop?
> Shop for L coins.
> thx

Yes, I plan to implement it :)
